                                    *** Concepts Covered ***
Tutorial 4 :  Split, Searching, Sorting

1. Split

In [12]:
import numpy as np

#1D

arr1=np.arange(8)
arr2=np.array_split(arr1,2)
arr2

[array([0, 1, 2, 3]), array([4, 5, 6, 7])]

In [7]:
arr3=np.array_split(arr1,4)
arr3

[array([0, 1]), array([2, 3]), array([4, 5]), array([6, 7])]

In [9]:
arr3[0]

array([0, 1])

In [11]:
arr3[1]

array([2, 3])

In [21]:
#2D
a1=np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [11, 12]])
a2=np.array_split(a1,4)
a2

[array([[1, 2],
        [3, 4]]),
 array([[5, 6],
        [7, 8]]),
 array([[ 9, 10]]),
 array([[11, 12]])]

In [24]:
#Split the 2-D array into three 2-D arrays along rows. -> alternate is hsplit(),vsplit()
arr=np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])
newarr = np.array_split(arr, 3, axis=1)
newarr

[array([[ 1],
        [ 4],
        [ 7],
        [10],
        [13],
        [16]]),
 array([[ 2],
        [ 5],
        [ 8],
        [11],
        [14],
        [17]]),
 array([[ 3],
        [ 6],
        [ 9],
        [12],
        [15],
        [18]])]

2. Array Searching

In [5]:
import numpy as np
arr=np.array([1,2,3,4,3])
x=np.where(arr==3)
x

(array([2, 4], dtype=int64),)

In [6]:
# Even values -> indices
y=np.where(arr%2==0)
y

(array([1, 3], dtype=int64),)

In [17]:
# Search in Sorted Array
zrr=np.array([1,2,3,4,5,6,7,8,9,10])
z=np.searchsorted(zrr,4)
z

3

In [14]:
# search from right side
zrr=np.array([1,2,3,4,5,6,7,8,9,10])
u=np.searchsorted(zrr,8,side="right")
u

8

In [18]:
# search multiple values
zrr=np.array([1,2,3,4,5,6,7,8,9,10])
v=np.searchsorted(zrr,[2,4,8])
v

array([1, 3, 7], dtype=int64)

3. Sorting

In [23]:
import numpy as np
crr=np.array([2,1,5,56,3])
np.sort(crr)

array([ 1,  2,  3,  5, 56])

In [25]:
drr=np.array(['banana','apple','mango','grape','orange','gauva'])
np.sort(drr)

array(['apple', 'banana', 'gauva', 'grape', 'mango', 'orange'],
      dtype='<U6')

In [26]:
err=np.array(['True','True','False','True','False'])
np.sort(err)

array(['False', 'False', 'True', 'True', 'True'], dtype='<U5')

In [27]:
frr=np.array([[3,5,1,],[4,0,9]])
np.sort(frr)

array([[1, 3, 5],
       [0, 4, 9]])