                                    *** Concepts Covered ***
Tutorial 3 : Datatypes, Copy, View, Shape, Reshape

1. Datatypes

In [3]:
import numpy as np

arr1=np.array([1,2,3,4,5])
arr1.dtype

dtype('int32')

In [9]:
arr2=np.array([[1,2,3,4]],dtype='S')
arr2.dtype

dtype('S1')

In [10]:
#TypeCasting
arr3=np.array([1.2,2.1,3.4,4.3])
arr3

array([1.2, 2.1, 3.4, 4.3])

In [11]:
arr4=arr3.astype('i')
arr4

array([1, 2, 3, 4], dtype=int32)

In [12]:
arr4.dtype

dtype('int32')

2. Copy

In [38]:
# Copy -> The copy owns the data and any changes made to the copy will not affect original array, 
#         and any changes made to the original array will not affect the copy.

a1=np.array([1,2,3,4])
c1=a1.copy()
a1[0]=10
a1

array([10,  2,  3,  4])

In [39]:
c1

array([1, 2, 3, 4])

3. View

In [40]:
# View - The view does not own the data and any changes made to the view will affect the original array, 
#        and any changes made to the original array will affect the view.

ar2=np.array([1,2,3,4])
cp2=ar2.view()
ar2[0]=10
ar2

array([10,  2,  3,  4])

In [41]:
cp2

array([10,  2,  3,  4])

4. Shape

In [4]:
import numpy as np

a=np.arange(10)
a.shape

(10,)

In [5]:
b=np.array([[1,2,3],[4,5,6]])
b.shape

(2, 3)

5. Reshape

In [6]:
# Reshape to 2D
arrr1=np.arange(12)
arrr2=arrr1.reshape(4,3)
arrr2

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [10]:
#Reshape to 3D
arrr3=arrr1.reshape(2,3,2)
arrr3

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]]])

In [12]:
#Flattening Array
arrr4=np.array([[1,2,3],[4,5,6]])
arrr5=arrr4.reshape(-1)
arrr5

array([1, 2, 3, 4, 5, 6])