                                    *** Concepts Covered ***
Tutorial 4 :  Split

1. Split

In [12]:
import numpy as np

#1D

arr1=np.arange(8)
arr2=np.array_split(arr1,2)
arr2

[array([0, 1, 2, 3]), array([4, 5, 6, 7])]

In [7]:
arr3=np.array_split(arr1,4)
arr3

[array([0, 1]), array([2, 3]), array([4, 5]), array([6, 7])]

In [9]:
arr3[0]

array([0, 1])

In [11]:
arr3[1]

array([2, 3])

In [21]:
#2D
a1=np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [11, 12]])
a2=np.array_split(a1,4)
a2

[array([[1, 2],
        [3, 4]]),
 array([[5, 6],
        [7, 8]]),
 array([[ 9, 10]]),
 array([[11, 12]])]

In [24]:
#Split the 2-D array into three 2-D arrays along rows. -> alternate is hsplit(),vsplit()
arr=np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])
newarr = np.array_split(arr, 3, axis=1)
newarr

[array([[ 1],
        [ 4],
        [ 7],
        [10],
        [13],
        [16]]),
 array([[ 2],
        [ 5],
        [ 8],
        [11],
        [14],
        [17]]),
 array([[ 3],
        [ 6],
        [ 9],
        [12],
        [15],
        [18]])]